## 데이터 가공
데이터를 보다 효과적으로 분석하기 위해 데이터를 변형하고 작업이 바로 **데이터 가공(data wrangling)** <br>
<br>
- gapminder 라이브러리 <br>
세계 각국의 기대 수명, 1인당 국내 총생산, 인구 데이터들을 집계해놓은 gapminder 데이터 셋의 일부를 담고 있음.

In [10]:
install.packages("gapminder")
library(gapminder)

package 'gapminder' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\uskaw\AppData\Local\Temp\RtmpY3lt9y\downloaded_packages

Warning message:
"package 'gapminder' was built under R version 3.6.3"

In [13]:
library(dplyr)

Warning message:
"package 'dplyr' was built under R version 3.6.3"
Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

In [14]:
glimpse(gapminder)  # glimpse(): 데이터 구조를 확인하는 함수로 str() 함수와 비슷하다.

Rows: 1,704
Columns: 6
$ country   <fct> "Afghanistan", "Afghanistan", "Afghanistan", "Afghanistan", ~
$ continent <fct> Asia, Asia, Asia, Asia, Asia, Asia, Asia, Asia, Asia, Asia, ~
$ year      <int> 1952, 1957, 1962, 1967, 1972, 1977, 1982, 1987, 1992, 1997, ~
$ lifeExp   <dbl> 28.801, 30.332, 31.997, 34.020, 36.088, 38.438, 39.854, 40.8~
$ pop       <int> 8425333, 9240934, 10267083, 11537966, 13079460, 14880372, 12~
$ gdpPercap <dbl> 779.4453, 820.8530, 853.1007, 836.1971, 739.9811, 786.1134, ~

#### 샘플과 속성의 추출
- 각 나라country 의 기대 수명 lifeExp

In [16]:
gapminder[, c("country", "lifeExp")]

     country     lifeExp
1    Afghanistan 28.801
2    Afghanistan 30.332
3    Afghanistan 31.997
4    Afghanistan 34.020
5    Afghanistan 36.088
6    Afghanistan 38.438
7    Afghanistan 39.854
8    Afghanistan 40.822
9    Afghanistan 41.674
10   Afghanistan 41.763
11   Afghanistan 42.129
12   Afghanistan 43.828
13   Albania     55.230
14   Albania     59.280
15   Albania     64.820
16   Albania     66.220
17   Albania     67.690
18   Albania     68.930
19   Albania     70.420
20   Albania     72.000
21   Albania     71.581
22   Albania     72.950
23   Albania     75.651
24   Albania     76.423
25   Algeria     43.077
26   Algeria     45.685
27   Algeria     48.303
28   Algeria     51.407
29   Algeria     54.518
30   Algeria     58.014
...  ...         ...
1675 Yemen, Rep. 49.113
1676 Yemen, Rep. 52.922
1677 Yemen, Rep. 55.599
1678 Yemen, Rep. 58.020
1679 Yemen, Rep. 60.308
1680 Yemen, Rep. 62.698
1681 Zambia      42.038
1682 Zambia      44.077
1683 Zambia      46.023
1684 Zambia      47.768
1685 Zambia      50.107
1686 Zambia      51.386
1687 Zambia      51.821
1688 Zambia      50.821
1689 Zambia      46.100
1690 Zambia      40.238
1691 Zambia      39.193
1692 Zambia      42.384
1693 Zimbabwe    48.451
1694 Zimbabwe    50.469
1695 Zimbabwe    52.358
1696 Zimbabwe    53.995
1697 Zimbabwe    55.635
1698 Zimbabwe    57.674
1699 Zimbabwe    60.363
1700 Zimbabwe    62.351
1701 Zimbabwe    60.377
1702 Zimbabwe    46.809
1703 Zimbabwe    39.989
1704 Zimbabwe    43.487

#### 샘플과 속성의 추출
- 행에는 이름이 지정되지 않은 경우가 많아 다음과 같이 행 번호를 <br>
지정하거나 조건식을 이용하는 것이 일반적

In [17]:
gapminder[1:15, ]

   country     continent year lifeExp pop      gdpPercap
1  Afghanistan Asia      1952 28.801   8425333  779.4453
2  Afghanistan Asia      1957 30.332   9240934  820.8530
3  Afghanistan Asia      1962 31.997  10267083  853.1007
4  Afghanistan Asia      1967 34.020  11537966  836.1971
5  Afghanistan Asia      1972 36.088  13079460  739.9811
6  Afghanistan Asia      1977 38.438  14880372  786.1134
7  Afghanistan Asia      1982 39.854  12881816  978.0114
8  Afghanistan Asia      1987 40.822  13867957  852.3959
9  Afghanistan Asia      1992 41.674  16317921  649.3414
10 Afghanistan Asia      1997 41.763  22227415  635.3414
11 Afghanistan Asia      2002 42.129  25268405  726.7341
12 Afghanistan Asia      2007 43.828  31889923  974.5803
13 Albania     Europe    1952 55.230   1282697 1601.0561
14 Albania     Europe    1957 59.280   1476505 1942.2842
15 Albania     Europe    1962 64.820   1728137 2312.8890

In [21]:
gapminder[gapminder$country == "Croatia" , "pop"] 
# 국가 이름이 "Croatia"인 샘플을 조건식을 사용해 추출 + 인구pop 속성만 추출

   pop
1  3882229
2  3991242
3  4076557
4  4174366
5  4225310
6  4318673
7  4413368
8  4484310
9  4494013
10 4444595
11 4481020
12 4493312

In [22]:
gapminder[gapminder$country == "Croatia" , c("lifeExp", "pop")]

   lifeExp pop
1  61.210  3882229
2  64.770  3991242
3  67.130  4076557
4  68.500  4174366
5  69.610  4225310
6  70.640  4318673
7  70.460  4413368
8  71.520  4484310
9  72.527  4494013
10 73.680  4444595
11 74.876  4481020
12 75.748  4493312

In [25]:
gapminder[gapminder$country == "Croatia" & gapminder$year > 1990 , c("lifeExp", "pop")] 
# Croatia의 1990년도 이후의 개대수명과 인구 추출

  lifeExp pop
1 72.527  4494013
2 73.680  4444595
3 74.876  4481020
4 75.748  4493312

- R에서 제공하는 apply 함수를 이용해 데이터 프레임에 포함된 여러 항목을 한꺼번에 연산 처리

In [27]:
apply(gapminder[gapminder$country == "Croatia", c("lifeExp", "pop")], 2, mean)

     lifeExp          pop
7.005592e+01 4.289916e+06

base R을 이용한 데이터 가공
- 데이터 가공은 데이터 프레임을 중심으로 R이 제공하는 다양한 연산자와 함수를 이용해서 이루어지는 작업
- 보다 정교하게 추출할려면 조건식 여러개를 논리 연산자로 결합
- 데이터를 타색하는 과정에서, 샘플들의 요약 통계 혹은 행/열 단위의 빠른 연산이 필요한 때가 있음
- R에서 제공하는 apply 함수를 이용하면 데이터 프레임을 구성하는 여러 항목을 한꺼번에 연산 가능

- base R의 데이터 가공 기법이 **인덱스 기반의 데이터 접근**에 기초하고 있다면, dplyr 라이브러리는 <br>
filter 혹은 select 가은 **입출력 관계의 함수**로 구현함으로써 사용자들이 보다 직관적으로 활용 가능

- 따라서 데이터 가공에 특화된 라이브러리를 사용하는 것이 더 효율적
- 탐색적 데이터 분석exploratory data analysis 과정에서 시각화와 데이터 가공은 매우 긴밀하게 <br>
연결되어 시각화를 위한 효유적인 가공 기법도 필요

#### 샘플과 속성 추출
- select 함수 이용
- 열을 지정할 때 " " 없이 열 이름을 그대로 사용할 수 있어 편리

In [38]:
select(gapminder, country, year, lifeExp) # select():열을 추출한다. 복수의 열을 추출할 때는 콤마로 구분하며,
# 인접열을 추출 할 때는 : 을 이용함.

     country     year lifeExp
1    Afghanistan 1952 28.801
2    Afghanistan 1957 30.332
3    Afghanistan 1962 31.997
4    Afghanistan 1967 34.020
5    Afghanistan 1972 36.088
6    Afghanistan 1977 38.438
7    Afghanistan 1982 39.854
8    Afghanistan 1987 40.822
9    Afghanistan 1992 41.674
10   Afghanistan 1997 41.763
11   Afghanistan 2002 42.129
12   Afghanistan 2007 43.828
13   Albania     1952 55.230
14   Albania     1957 59.280
15   Albania     1962 64.820
16   Albania     1967 66.220
17   Albania     1972 67.690
18   Albania     1977 68.930
19   Albania     1982 70.420
20   Albania     1987 72.000
21   Albania     1992 71.581
22   Albania     1997 72.950
23   Albania     2002 75.651
24   Albania     2007 76.423
25   Algeria     1952 43.077
26   Algeria     1957 45.685
27   Algeria     1962 48.303
28   Algeria     1967 51.407
29   Algeria     1972 54.518
30   Algeria     1977 58.014
...  ...         ...  ...
1675 Yemen, Rep. 1982 49.113
1676 Yemen, Rep. 1987 52.922
1677 Yemen, Rep. 1992 55.599
1678 Yemen, Rep. 1997 58.020
1679 Yemen, Rep. 2002 60.308
1680 Yemen, Rep. 2007 62.698
1681 Zambia      1952 42.038
1682 Zambia      1957 44.077
1683 Zambia      1962 46.023
1684 Zambia      1967 47.768
1685 Zambia      1972 50.107
1686 Zambia      1977 51.386
1687 Zambia      1982 51.821
1688 Zambia      1987 50.821
1689 Zambia      1992 46.100
1690 Zambia      1997 40.238
1691 Zambia      2002 39.193
1692 Zambia      2007 42.384
1693 Zimbabwe    1952 48.451
1694 Zimbabwe    1957 50.469
1695 Zimbabwe    1962 52.358
1696 Zimbabwe    1967 53.995
1697 Zimbabwe    1972 55.635
1698 Zimbabwe    1977 57.674
1699 Zimbabwe    1982 60.363
1700 Zimbabwe    1987 62.351
1701 Zimbabwe    1992 60.377
1702 Zimbabwe    1997 46.809
1703 Zimbabwe    2002 39.989
1704 Zimbabwe    2007 43.487

#### 샘플과 속성 추출
- 특정 샘플(행)을 추출할 때는 filter 함수 사용
- 조건식 구성은 base R과 유사하나 함수 내에서 인덱싱을 위해 데이터 프레임의<br>
이름을 매번 입력하지 않아도 되므로 명령어가 간결

In [39]:
filter(gapminder, country == "Croatia") # filter(): 조건에 따라 행을 추출한다.

   country continent year lifeExp pop     gdpPercap
1  Croatia Europe    1952 61.210  3882229  3119.237
2  Croatia Europe    1957 64.770  3991242  4338.232
3  Croatia Europe    1962 67.130  4076557  5477.890
4  Croatia Europe    1967 68.500  4174366  6960.298
5  Croatia Europe    1972 69.610  4225310  9164.090
6  Croatia Europe    1977 70.640  4318673 11305.385
7  Croatia Europe    1982 70.460  4413368 13221.822
8  Croatia Europe    1987 71.520  4484310 13822.584
9  Croatia Europe    1992 72.527  4494013  8447.795
10 Croatia Europe    1997 73.680  4444595  9875.605
11 Croatia Europe    2002 74.876  4481020 11628.389
12 Croatia Europe    2007 75.748  4493312 14619.223

In [40]:
summarize(gapminder, pop_avg=mean(pop))

  pop_avg
1 29601212

In [41]:
summarize(group_by(gapminder, continent), pop_avg=mean(pop))

  continent op_avg
1 Africa     9916003
2 Americas  24504795
3 Asia      77038722
4 Europe    17169765
5 Oceania    8874672

#### 행/열 단위의 연산
- groupby 함수를 이용하면 데이터 프레임에 포함된 factor 형 속성을 활용 <br>
전체 데이터를 그룹으로 분류 가능
- 보통 summarise 함수를 연이어 사용해 그룹별 통계 지표를 한번에 산출

In [50]:
summarise(gapminder, pop_avg = mean(pop))

  pop_avg
1 29601212

In [51]:
summarise(group_by(gapminder ,continent), pop_avg = mean(pop)) # factor 요소 값 별로 통계를 내준다.

  continent pop_avg
1 Africa     9916003
2 Americas  24504795
3 Asia      77038722
4 Europe    17169765
5 Oceania    8874672

In [53]:
summarise(group_by(gapminder ,continent, country), pop_avg = mean(pop)) # factor 요소 값 별로 통계를 내준다.

`summarise()` has grouped output by 'continent'. You can override using the `.groups` argument.

    continent country                  pop_avg
1   Africa    Algeria                  19875406.2
2   Africa    Angola                    7309390.1
3   Africa    Benin                     4017496.7
4   Africa    Botswana                   971186.2
5   Africa    Burkina Faso              7548677.2
6   Africa    Burundi                   4651608.3
7   Africa    Cameroon                  9816648.4
8   Africa    Central African Republic  2560963.0
9   Africa    Chad                      5329256.3
10  Africa    Comoros                    361683.9
11  Africa    Congo, Dem. Rep.         32681655.2
12  Africa    Congo, Rep.               1923209.1
13  Africa    Cote d'Ivoire             9153109.5
14  Africa    Djibouti                   260243.9
15  Africa    Egypt                    46522774.2
16  Africa    Equatorial Guinea          327551.0
17  Africa    Eritrea                   2820216.8
18  Africa    Ethiopia                 41632518.8
19  Africa    Gabon                      795415.4
20  Africa    Gambia                     793138.6
21  Africa    Ghana                    12616626.4
22  Africa    Guinea                    5360550.7
23  Africa    Guinea-Bissau              882008.4
24  Africa    Kenya                    18206250.2
25  Africa    Lesotho                   1389696.4
26  Africa    Liberia                   1813857.2
27  Africa    Libya                     3166803.6
28  Africa    Madagascar                9902402.2
29  Africa    Malawi                    7016377.4
30  Africa    Mali                      7112340.1
... ...       ...                      ...
113 Europe    Belgium                   9725118.7
114 Europe    Bosnia and Herzegovina    3816524.8
115 Europe    Bulgaria                  8182985.3
116 Europe    Croatia                   4289916.2
117 Europe    Czech Republic            9986262.8
118 Europe    Denmark                   4994187.3
119 Europe    Finland                   4771321.0
120 Europe    France                   52952564.3
121 Europe    Germany                  77547043.3
122 Europe    Greece                    9424181.1
123 Europe    Hungary                  10217645.7
124 Europe    Iceland                    226978.1
125 Europe    Ireland                   3340825.9
126 Europe    Italy                    54536958.0
127 Europe    Montenegro                 564269.7
128 Europe    Netherlands              13786797.9
129 Europe    Norway                    4031441.1
130 Europe    Poland                   34323304.4
131 Europe    Portugal                  9586273.9
132 Europe    Romania                  20819090.2
133 Europe    Serbia                    8783886.8
134 Europe    Slovak Republic           4774507.1
135 Europe    Slovenia                  1794381.4
136 Europe    Spain                    35851798.4
137 Europe    Sweden                    8220028.9
138 Europe    Switzerland               6384293.2
139 Europe    Turkey                   45909008.2
140 Europe    United Kingdom           56087800.7
141 Oceania   Australia                14649312.5
142 Oceania   New Zealand               3100032.2

#### %>% 연산자를 이용한 연속처리
 - %>% 연산자를 이용한 일련의 가공 작업을 연결
chain(pipe) operator(%>%) : 여러 단계 절차가 필요한 중간결과 저장후 그 객체를 후속 절차에서<br>
받아 사용해야 하는 경우 유용함

In [66]:
gapminder%>% group_by(continent, country) %>% summarize(pop_avg = mean(pop))

`summarise()` has grouped output by 'continent'. You can override using the `.groups` argument.

    continent country                  pop_avg
1   Africa    Algeria                  19875406.2
2   Africa    Angola                    7309390.1
3   Africa    Benin                     4017496.7
4   Africa    Botswana                   971186.2
5   Africa    Burkina Faso              7548677.2
6   Africa    Burundi                   4651608.3
7   Africa    Cameroon                  9816648.4
8   Africa    Central African Republic  2560963.0
9   Africa    Chad                      5329256.3
10  Africa    Comoros                    361683.9
11  Africa    Congo, Dem. Rep.         32681655.2
12  Africa    Congo, Rep.               1923209.1
13  Africa    Cote d'Ivoire             9153109.5
14  Africa    Djibouti                   260243.9
15  Africa    Egypt                    46522774.2
16  Africa    Equatorial Guinea          327551.0
17  Africa    Eritrea                   2820216.8
18  Africa    Ethiopia                 41632518.8
19  Africa    Gabon                      795415.4
20  Africa    Gambia                     793138.6
21  Africa    Ghana                    12616626.4
22  Africa    Guinea                    5360550.7
23  Africa    Guinea-Bissau              882008.4
24  Africa    Kenya                    18206250.2
25  Africa    Lesotho                   1389696.4
26  Africa    Liberia                   1813857.2
27  Africa    Libya                     3166803.6
28  Africa    Madagascar                9902402.2
29  Africa    Malawi                    7016377.4
30  Africa    Mali                      7112340.1
... ...       ...                      ...
113 Europe    Belgium                   9725118.7
114 Europe    Bosnia and Herzegovina    3816524.8
115 Europe    Bulgaria                  8182985.3
116 Europe    Croatia                   4289916.2
117 Europe    Czech Republic            9986262.8
118 Europe    Denmark                   4994187.3
119 Europe    Finland                   4771321.0
120 Europe    France                   52952564.3
121 Europe    Germany                  77547043.3
122 Europe    Greece                    9424181.1
123 Europe    Hungary                  10217645.7
124 Europe    Iceland                    226978.1
125 Europe    Ireland                   3340825.9
126 Europe    Italy                    54536958.0
127 Europe    Montenegro                 564269.7
128 Europe    Netherlands              13786797.9
129 Europe    Norway                    4031441.1
130 Europe    Poland                   34323304.4
131 Europe    Portugal                  9586273.9
132 Europe    Romania                  20819090.2
133 Europe    Serbia                    8783886.8
134 Europe    Slovak Republic           4774507.1
135 Europe    Slovenia                  1794381.4
136 Europe    Spain                    35851798.4
137 Europe    Sweden                    8220028.9
138 Europe    Switzerland               6384293.2
139 Europe    Turkey                   45909008.2
140 Europe    United Kingdom           56087800.7
141 Oceania   Australia                14649312.5
142 Oceania   New Zealand               3100032.2

In [97]:
options(digits=5) # 소수점 5번째에서 반올림 출력

In [98]:
temp1 = filter(gapminder, country=="Croatia")
temp2 = select(temp1, country, year, lifeExp)
temp3 = apply(temp2[, c("lifeExp")], 2, mean)
print(temp3)

lifeExp
 70.056

In [99]:
gapminder %>% filter(country == "Croatia") %>% 
select(country ,year, lifeExp) %>% summarise(lifeExp_avg = mean(lifeExp)) # R 다운 코드!

  lifeExp_avg
1 70.056